name: 'Drupal 8'
slug: drupal_8
cron: sfsdfsdfsd
public_folder: ''
database_required: true

additional_config: |
 $settings['update_free_access'] = FALSE;
 ini_set('session.gc_probability', 1);
 ini_set('session.gc_divisor', 100);
 ini_set('session.gc_maxlifetime', 200000);
 ini_set('session.cookie_lifetime', 2000000);
 $config['system.performance']['fast_404']['exclude_paths'] = '/\/(?:styles)|(?:system\/files)\//';
 $config['system.performance']['fast_404']['paths'] = '/\.(?:txt|png|gif|jpe?g|css|js|ico|swf|flv|cgi|bat|pl|dll|exe|asp)$/i';
 $config['system.performance']['fast_404']['html'] = '<!DOCTYPE html><html><head><title>404 Not Found</title></head><body><h1>Not Found</h1><p>The requested URL "@path" was not found on this server.</p></body></html>';
 $config['user.flood']['ip_limit'] = 50;
 $config['user.flood']['ip_window'] = 3600;
 $config['user.flood']['user_limit'] = 10;
 $config['user.flood']['user_window'] = 10800;
 $settings['allow_authorize_operations'] = FALSE;

directories: #allows the use of [[user]]
  - "/home/[[user]]/.drush"


other: sdf